### ISSUE TITLE
adding vitables into environment file

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/ctapipe#1340]
is there a reason why we are not adding _vitables_ as a dependency to read the products of the writer scripts?

Are there other candidates and we leave this choice to the (low-level)-users?

**Comment by MaxNoe** [comment]
Why should we add a command line utility to look into files as a dependency? It's not.

**Comment by HealthyPear** [comment]
Yes sorry it's not a dependency...
I meant into the environment file

**Comment by kosack** [comment]
actually, it's not a bad idea.  Originally I did not do it since vitables conflicted with many packages, but that's been improved recently, so we could add it for the release, so people have an environment out-of-the-box that can generate and view vitables (same reason we have pandas in there, in fact, even though it's not a dep)
