### ISSUE TITLE
HDF5 Table Reader does not clear container when column is missing

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1742]
When reading a table with a missing column (e.g. because it was None) the `HDF5TableReader` does not clear the container field.

This results in wrong behavior since it also reuses the same container instance over and over.

If reading a dl1 file with only images (which has no `image_mask`) column and then setting the image_mask, it is kept for all following rows in the file.

This broke the muon tool when the input only contained images:
```
        if dl1.image_mask is None:
            dl1.image_mask = self.cleaning(tel_id, image)

```

**Comment by kosack** [comment]
probably we should just return a whole new container each time, that way the defaults are correct.  I had originally thought that would add too much overhead, so opted for re-using a user-provided container, but that seems to be error prone.  Otherwise, passing in a new container each time will also fix it.
