### ISSUE TITLE
Writing of the table indices breaks 

### ISSUE THREAD

**Issue by TjarkMiener** [cta-observatory/ctapipe#2067]
**Describe the bug**
When writing a DL1 file with ctapipe v0.16.0 and setting the flag `write-index-tables` to True, pytables is breaking.

**To Reproduce**
1. `$ ctapipe-process -i /data3/users/nieto/Prod5b_sample/Prod5b_LaPalma_AdvancedBaseline_NSB1x_gamma_North_20deg_DL0_1e6evt/gamma_20deg_0deg_run126___cta-prod5b-lapalma_desert-2158m-LaPalma-dark.simtel.zst --progress --write-images --write-parameters --write-index-tables`

**Supporting information**
<img width="1080" alt="Screenshot 2022-08-31 at 12 07 02" src="https://user-images.githubusercontent.com/37835610/188490199-d85305c0-8d0a-4592-b403-14804905a720.png">

**Comment by maxnoe** [comment]
this is somehow triggered by setting the `HDFTableWriter` instance of `DataWriter` to `None` in `DataWriter.finish`.

This really looks like a tables bug but I couldn't yet produce a minimal example triggering this bug and it's very strange to me that this only happens when creating the indices...

But removing that fixes this annoying error spam.
