### ISSUE TITLE
Single pixels in Cleaned Images

### ISSUE THREAD

**Issue by ParsonsRD** [cta-observatory/ctapipe#248]
As mentioned at the pipeline meeting, currently the split level image cleaning algorithm is implemented in such a way that it is possible to have single pixels with no significant neighbours. Although it is not a bug as such is can cause problems when setting aggressive cleaning thresholds.

It would also be nice to allow the HESS-style option where it is required that each pixel have a significant neighbour.

I will try adding this as an option to the cleaning code, as I think it just requires another loop to remove these pixels from the mask.

**Comment by kosack** [comment]
It would be good to implement that as a separate algorithm in `cleaning.py`, so we can compare, rather than adding options to the current algorithm.  The currently implemented algorithm is the "whipple-style" picture/boundary cleaning, so having a separate Hegra-style "tail-cuts" algorithm could be nice. 

The other possibility is to add a second function that modifies the results of the initial cleaning (like the `dilate` function). In whipple this was called "island cleaning", which removed all but the largest island.

**Comment by kosack** [comment]
generally, if there are single pixels left, it means the thresholds are set too high.  In the whipple-style algorithm, the intention is not to use, fixed values for the thresholds in PE, but rather fractions of the median value of the pedestal variances for that image (which is why the pedvars are passed in).  The defaults in whipple were picture=5.0% median pedvar, and boundary=2.5% median pedvar.  That does leave some possibility for single pixel fluctuations though,

**Comment by GernotMaier** [comment]
Here the link to Isabel's paper on the island cleaning:
http://adsabs.harvard.edu/abs/2003APh....20..311B
