### ISSUE TITLE
need a way to store telescope patterns/lists in an output table

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#252]
Currently a few containers contain a list of telescopes that were e.g.:
* triggered
* read out
* used in reconstruction
* used in classification

These should end up in the output file, but so far the data formats chosen (FITS, HDF5) don't have a good way to store a column with a variable-length array in it (it's very inefficient in FITS, a bit better in HDF5, but very few tools support reading it).  Should we use a more serializable representation?

*  a fixed-length bitfield (each bit representing a telescope), would need to be at least the number of bits as there are telescopes
*  stick with var-length arrays, but take the performance hit?
* other ideas?

**Comment by MaxNoe** [comment]
This is a problem for DL1, correct? As DL2 is by definition tabular as far as I understood.

**Comment by contrera** [comment]
In principle the fixed-length bitfield looks better suited for me since, even if size is not an important issue because these lists should appear once (or at most a few times) per event. I do not know if this may cause performance issues.

One possibility to explore is if the length of the field can be different in CTA-N and CTA-S.

 Q: ¿ If a fixed length array is used (instead of a bitfield) won´t HDF5 or CFITs compressed it efficiently ?  

  

 

-

**Comment by maxnoe** [comment]
This is done now.
