### ISSUE TITLE
Neighbour calibration

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/ctapipe#567]
Testing the neighbour calibration in ctapipe, here is what I obtain:
![ctapipe_calib](https://user-images.githubusercontent.com/4263646/31493091-0015d6fa-af4e-11e7-9fc1-6444739f622a.png)

Some distribution shapes are unexpected (CHEC, DigiCam, NectarCam) and do not look physical. Errors might come from simulations also. 
Note that re-coding the neighbour calibration in C++ (HPC), we get similar results for LSTCam, CHEC and DigiCam but more realistic distributions for NectarCam and FlashCam.

For now I do not know where the issue might come from.

**Comment by kosack** [comment]
Can you tell me what are these plots? Are tehy from a single pixel on a single camera, summed over events, or combined all pixels?  They look fine to me (mostly)  just recall the CHEC + Digicam use SiPms, where you see the 1,2,3,4,5 - up to 30PE peak if you have stats, whereas the regular PMs get washed out. Flashcam looks too wide, but that is to be expected since we don't yet support it's method, or perhaps there is a bug.

**Comment by vuillaut** [comment]
Hi.
Sorry I should have said that these plots are the result of the neighbour method calibration for the whole cameras and for many events. The Y axis is normed.
I expected something like LSTCam.
- FlashCam is much wider that what we get with our algo
- The sharp shape at ~ -2pe for the NectarCam looks weird to me and we don't get it either with our calibration

Here is the comparison:
![compared_calib](https://user-images.githubusercontent.com/4263646/31500671-53707ba6-af68-11e7-8792-82586e6d1680.png)

**Comment by kosack** [comment]
I've never seen the sharp edge in nectar cam with any of the data I've looked at.  I just tried and can't reproduce it, though if the NSB is turned off, I would expect to see a sharp cutoff, since you cannot have less than 1 PE at the photocathode - you only get a smooth/negative distribution if there is some NSB on top being subtracted.  Which data files are you using? It definitely looks like a problem in one or the other code.  ASTRICam is of course normal, since you can't do any trace integration on it, so the NeighborPeak scheme is not usable. 

@watsonjj how much testing / cross-checks have you done with non-CHEC camera data with NeighborPeak integration?   Certainly there is something strange going on here in all cameras (none agree well).   One easy thing to do is to test it against what is done in `read_hess` or `

**Comment by kosack** [comment]
see for example https://github.com/cta-observatory/ctapipe/blob/master/examples/notebooks/check_calib.ipynb

**Comment by kosack** [comment]
Also, can you post a link to your neighbor-peak integration code? It's hard to compare without knowing if the algorithm is the same (there are many ways to do it)

**Comment by watsonjj** [comment]
This is a little weird...I agree. It is like you are seeing the low illumination spectra of the camera...but you have masked out the cherenkov shower... so the only thing that should remain is the NSB, which shouldn't be coincident in neighbouring pixels, and so it shouldn't be visible with the NeighbourPeakIntegrator...

Using that notebook, it certainly as visible when using a LocalPeakIntegrator, making this even more stranger...

I personally haven't checked the integrators against read_hess. But Rachel had back when she worked on the code. Though, I do imagine they may not return the same values anymore, as I reinterpreted the code to achieve a similar method utilising numpy.

**Comment by watsonjj** [comment]
Could I have the sim_telarray file you are using?

**Comment by maxnoe** [comment]
@vuillaut @watsonjj This is a very old issue about a calibration artifact. Much has changed since then.

I will close this, feel free to reopen if you think this is still an issue. But at least a current comparison should then be included.
