### ISSUE TITLE
docu: getting started - inconsistency?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#585]
In the getting started area one can read here https://github.com/dneise/ctapipe/blame/master/docs/getting_started/index.rst#L81

One should to this

    conda env create -n cta-dev -f environment.yml

In the environmen.yml the name is given as `ctadev` without the dash. Isn't this an inconsistency?

The conda docu https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

seems to recommend not to use the `-n --name` cmdline option...

**Comment by kosack** [comment]
If you don't use the `-n` option, it uses the name in the environment file.  I kept the name in the instructions just because during deployment we often need to create multiple environments with different names (that's how it's currently installed on the grid), but yes, it should probably be consistent, or we should put a place-holder in so the user can decide like `conda create -n <my environment name> -f environment.yml`

In any, case we don't have many users yet since we won't have a stable release for a while, so probably most install via the developer instructions. At least no users should be relying on things working  in a consistent or useful way yet :-)
