### ISSUE TITLE
instrument.optics: Does this test contradict the implementation?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#605]
Tests serve a docu to me, so I tend to believe what ever the test says is right, but here I was a bit puzzled:

**test**
```python
    with pytest.raises(KeyError):
        OpticsDescription.guess(0*u.m)
```

This seems clear, when we give a wrong focal length, we get a KeyError, plain and simple.

----
**implementation**: abbreviated
```python
class OpticsDescription
    @classmethod
    def guess(cls, equivalent_focal_length):
        tel_type = telescope_info_from_metadata(equivalent_focal_length)
        if tel_type == "unknown":
            logger.warning("setting tel_type to unknown")
        return cls(tel_type, equivalent_focal_length)
```
No key error ... just a warning.

Maybe deeper?
```python
def telescope_info_from_metadata(focal_length):
    return _FOCLEN_TO_TEL_INFO[round(focal_length.to('m').value, 2)]
```

yes, this raises the KeyError. It can not return the string "unknown". 
If it would return the string "unknown" instead of throwing KeyError, e.g. like this

```python
def telescope_info_from_metadata(focal_length):
    try:
        return _FOCLEN_TO_TEL_INFO[round(focal_length.to('m').value, 2)]
    except KeyError:
        return "unknown"
```

Then the "unknown" would bubble up into the `__init__`:
```python
    def __init__(self, tel_type, ...):
        if tel_type not in ['LST', 'MST', 'SST']:
            raise ValueError("Unknown tel_type %s", tel_type)
```

and throw a `ValueError` not a KeyError. 

-----

So the test says: on wrong key --> KeyError
implementation suggests ... could also be ValueError

What was the authors intention?

**Comment by kosack** [comment]
That does seem quite confusing! I'm not sure what I had intended :-)  

I think in the end `guess()`  should throw a KeyError, since it takes some key metadata to use to find the resulting optics info, and `__init__()` should still throw a `ValueError`, since it is an incorrect value that is being tested (sort of like an enum, which in python the enum module throws ValueErrors on incorrect input).  The tests need to be updated to test both cases.  I'll see if I can clean it up so it's less confusing (there should just be a single path of failure).

I also think that `guess()` should simply fail if an unknown focal length is passed in, since it makes no sense to create a crazy telescope (which could of course be done by hand using the constructor if really needed), so I'll remove the "unknown" line.
