### ISSUE TITLE
PointingContainer not filled by HessioEventSource

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#823]
The PointingContainer is empty for `HESSIOEventSource`

**Comment by kosack** [comment]
It's deprecated, I think.  The pointing positions are not top-level, but can be different for each camera due to mispointing or divergent pointing, slewing etc.  So we should get rid of it. It think there was an issue about that, but can't find it. In any case, the pointing container should never be used.

**Comment by MaxNoe** [comment]
As discussed  in Dortmund, we will use the per-telescope pointing container.
