### ISSUE TITLE
Circular import around ctapipe.core.Container

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#89]
### `ctapipe.io.__init__`:
```
from .containers import *
```
### `ctapipe.io.containers`:
```
from ctapipe.core import Container
```

### `ctapipe.core.__init__`

```
from ctapipe.io.files import get_file_type
```

**Comment by kosack** [comment]
Is there a suggestion how to resolve this? Originally `io` only depended on `core` and not the other way around, but now there is a loop.

The problem seems only to be that in `core.container` the `write()` method uses `io.get_file_type()`. Either we need to separate the writing of containers (delegating any writing to some back-end written in io), or move `get_file_type()` to `core`...
