### ISSUE TITLE
predict in reco_algorithms

### ISSUE THREAD

**Issue by thomasgas** [cta-observatory/ctapipe#924]
All reconstruction algorithms are expected to overwrite this method:

https://github.com/cta-observatory/ctapipe/blob/5849db486586bc94737d171e611cc782bbe927fa/ctapipe/reco/reco_algorithms.py#L11

But the reconstruction algorithms don't overwrite this method in the required way:
https://github.com/cta-observatory/ctapipe/blob/59931737dee8b27c5e36655a538c87aee9c2c440/ctapipe/reco/ImPACT.py#L618
https://github.com/cta-observatory/ctapipe/blob/59931737dee8b27c5e36655a538c87aee9c2c440/ctapipe/reco/HillasReconstructor.py#L95
https://github.com/cta-observatory/ctapipe/blob/59931737dee8b27c5e36655a538c87aee9c2c440/ctapipe/reco/hillas_intersection.py#L52

How do we want to deal with this issue?
Substituting `tels_dicts` with `**args` solves this but it's a pretty bad fix (i guess).
Any ideas?

**Comment by kosack** [comment]
Since the interface is really different for each, it's clear that this method probably is not appropriate for a virtual method, at least in the current implementation. It's more of just a guideline that there should be some method named predict for each one, but doesn't enforce any interface for that. 

This points to a need to refactor the Reconstructor class hierarchy.  I think it still makes sense to have a base class for these, since  they could share a lot of things, particuarly the output, which should be the same for each.  The question I would have is if we can refactor all Reconstructors to have a more common interface for `predict()`, that works with all types of reconstructors?  Or just take it out of the base class, and say that all reconstructors should define a predict() method that is appropriate? 

I guess the original idea was to make it as similar to scikit-learn classes as possible (e.g. having a `train()` and `predict()` method, so that a user/developer isn't confused as to how to use it.

**Comment by thomasgas** [comment]
In #946 I've refactored a bit the reconstructors so that the same input can be given to both of them (was not the case before). I moved some stuff inside the `HillasIntersection` class, so that the predict method would be something like:
`def predict(self, hillas_dict, inst, array_pointing, telescopes_pointings=None):`
And if the `telescopes_pointings` are not provided, they are copied from the `array_pointing`, so that the code is independent from this input. This is not a final fix since we should have a better handling of the pointing container somehow...

**Comment by maxnoe** [comment]
I am closing. We changed the API of `Reconstructor` to be `__call__(self, event: ArrayEventContainer)` and have a dedicated issue discussing further improvements here:

https://github.com/cta-observatory/ctapipe/issues/2116
